# This YAML file contains all API objects that are necessary to run kube-dag.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-dag

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-dag
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete", "update"]
  - apiGroups: ["execution.kubegene.io"]
    resources: ["executions"]
    verbs: ["get", "list", "watch", "update", "delete"]
  - apiGroups: ["execution.kubegene.io"]
    resources: ["executions/status"]
    verbs: ["update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-dag-role
subjects:
  - kind: ServiceAccount
    name: kube-dag
    # replace with non-default namespace name
    namespace: default
roleRef:
  kind: ClusterRole
  name: kube-dag
  apiGroup: rbac.authorization.k8s.io

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-dag
spec:
  replicas: 1
  selector:
    matchLabels:
      kube-dag: test
  template:
    metadata:
      labels:
        kube-dag: test
    spec:
      serviceAccount: kube-dag
      containers:
        - name: kube-dag
          image: kube-dag:v1
          args:
            - "--v=4"
          env:
            - name: MY_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: "IfNotPresent"


